export default {
    collectCoverage: true,
    coverageDirectory: "coverage",
    coveragePathIgnorePatterns: ["\\\\node_modules\\\\"],
    coverageProvider: "v8",
    coverageReporters: ["json", "text", "lcov", "clover"],
    moduleFileExtensions: [
      "js",
    //   "mjs",
    //   "cjs",
      "jsx",
      "ts",
      "tsx",
      "json",
      "node",
    ],
    preset: "ts-jest",
    testEnvironment: "jsdom",
    testMatch: ["**/__tests__/**/*.[jt]s?(x)", "**/?(*.)+(spec|test).[tj]s?(x)"],
    testPathIgnorePatterns: ["\\\\node_modules\\\\"],
    moduleDirectories: ["node_modules", "src"],
    modulePaths: [ "<rootDir>/src" ],
  };